<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="example_loop_control" Id="{f4111f27-f002-47e1-985a-deb6fca944d4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM example_loop_control
VAR
	//Example run request for a starter motor.  This would be triggered by control loop logic
	u_3160_run_request : BOOL;
	
	//Example run request for a vfd motor.  This would be triggered by control loop logic
	u_3112_run_request : BOOL;
	//Example Speed Request for a vfd motor.  This would be set by control loop logic, normally a PID
	u_3112_speed_request : REAL;
	
	//Example position request for an analog valve.  This would be set by control loop logic, normally a PID
	av_3148_position_request : REAL;
	
	//Example open request for a digital valve.  This would be triggered by control loop logic
	nv_3372_open_request : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>