<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="valve_digital_control_st" Id="{8f0a8d66-a59e-41d2-8b25-85917edd7a47}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM valve_digital_control_st
VAR PERSISTENT

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Instantiate motor vfd function block, and map inputs
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>