<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="valve_analog_control_st" Id="{687397f5-3c81-4587-973c-34cb591a9a0c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM valve_analog_control_st
VAR PERSISTENT

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Instantiate valve analog function block, and map inputs
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>